#!/bin/bash

# Test script for RSS search functionality
# This script helps test the search feature and shows you what to look for

echo "=== RSS Feed Search Test Script ==="
echo ""
echo "Before running this script:"
echo "1. Start the server: ./bin/server -port 4000"
echo "2. Open http://localhost:4000 in your browser"
echo "3. Create an account and login"
echo "4. Navigate to /feeds/search"
echo ""
echo "Expected behavior:"
echo ""
echo "Test 1: Search for known feed"
echo "  - Enter: techcrunch"
echo "  - Should see: Known feed results"
echo "  - Logs should show: 'searched known feeds' with results_count=1"
echo ""
echo "Test 2: Search for URL (trigger discovery)"
echo "  - Enter: https://news.ycombinator.com/rss"
echo "  - Should see: Discovery starts"
echo "  - Logs should show:"
echo "    * 'should_discover=true'"
echo "    * 'attempting to enqueue job'"
echo "    * 'job enqueued successfully'"
echo "    * 'worker processing job'"
echo "    * 'executing discovery job'"
echo ""
echo "If nothing happens when clicking search:"
echo "  - Check browser console for JavaScript errors"
echo "  - Check server logs for any errors"
echo "  - Look for 'received search POST request' in logs"
echo "  - If no POST request logged, check CSRF token"
echo ""
echo "Common issues to check in logs:"
echo "  1. 'search query is empty' - Form not submitting correctly"
echo "  2. 'should_discover=false' - Check why discovery not triggered"
echo "  3. 'job already in-flight' - Discovery already running"
echo "  4. No POST logs - JavaScript preventing submission or CSRF issue"
echo ""
echo "To see live logs while testing:"
echo "  ./bin/server -port 4000 | grep -E '(search|discover|queue|job)'"
echo ""
